apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: betflix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: betflix
  minReplicas: 60
  maxReplicas: 120
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
